[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "arm-none-eabi-gdb -q -x run.gdb"
rustflags = [
    "-C", "linker=arm-none-eabi-gcc",
    "-C", "link-arg=-Wl,-Tlink.x",
    "-C", "link-arg=-nostartfiles",
]

[build]
target = "thumbv8m.main-none-eabihf"