[package]
name = "efr32mg24b210f1536im48-sys"
version = "0.1.0"
edition = "2021"

[dependencies]
critical-section = { version = "1.0", optional = true }
cortex-m = "0.7"
cortex-m-rt = { version = "0.7", optional = true }
vcell = "0.1.2"

[features]
rt = ["cortex-m-rt/device"]
